name: Auto Merge to Main

on:
  push:
    branches:
      - stage

jobs:
  merge_to_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge stage into main
        run: |
          git checkout main
          git merge --no-ff stage -m "Merge changes from stage to main"
          git push origin main
